"""Add api_key to Users model

Revision ID: f514c89a5aef
Revises: 6984a26a1e00
Create Date: 2025-09-18 18:49:57.550208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f514c89a5aef'
down_revision = '6984a26a1e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_key'))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
